export const SIGN_IN = 'SIGN_IN';
export const REFRESH_TOKEN = 'REFRESH_TOKEN ';
export const ERROR = 'ERROR';
export const LOG_OUT = 'LOG_OUT';
export const LOADING_LOGIN = 'LOADING_LOGIN';

export const SELECT_COMPANY = 'SELECT_COMPANY';
export const RELOAD_COMPANY = 'RELOAD_COMPANY';
export const REFRESH_IDCONNECTION = 'REFRESH_IDCONNECTION';


//signalr =====================================

export const ARBOL = 'ARBOL';
export const TREE_PARTS = 'TREE_PARTS';
export const DATA_GENERAL = 'DATA_GENERAL';
export const ID_DATA_TABLE = 'ID_DATA_TABLE';
export const TREE_COUNT = 'TREE_COUNT';
export const LISTAR_POR_PERIODO = 'LISTAR_POR_PERIODO';
export const PROJECT_DETAILS = 'PROJECT_DETAILS';
export const LIST_HISTORY = 'LIST_HISTORY';

export const LIMPIA_PARTY_CONTROL = 'LIMPIA_PARTY_CONTROL';
export const PARTY_CONTROL = 'PARTY_CONTROL';
export const PARTY_CONTROL1 = 'PARTY_CONTROL1';

export const LISTAR_SUBS = 'LISTAR_SUBS';
export const LIMPIAR_SUBS = 'LIMPIAR_SUBS';

export const LISTAR_CLIENTES = 'LISTAR_CLIENTES';
export const LISTAR_UBICACIONES = 'LISTAR_UBICACIONES';
export const LIMPIAR_UBICACIONES = 'LIMPIAR_UBICACIONES';

export const LISTAR_MODELOS = 'LISTAR_MODELOS';

export const LISTAR_MONEDAS = 'LISTAR_MONEDAS';


export const LEER_PRESUPUESTO = 'LEER_PRESUPUESTO';
export const ACT_PRESUPUESTO = 'ACT_PRESUPUESTO';

export const CAMBIA_SELECCION = 'CAMBIA_SELECCION';
export const SUB_SEL = 'SUB_SEL';


export const MENSUAL_DETALLE = 'MENSUAL_DETALLE';
export const APU_DETALLE = 'APU_DETALLE';

export const METRADO_DETALLE = 'METRADO_DETALLE';
export const METRADO_LIMPIAR = 'METRADO_LIMPIAR';

export const UNIQUE_DETALLE = 'UNIQUE_DETALLE';

export const ASOCIADO_DETALLE = 'ASOCIADO_DETALLE';
export const ESTRUCTURA_DETALLE = 'ESTRUCTURA_DETALLE';
export const CALCULO_DETALLE = 'CALCULO_DETALLE';
export const CALCULODET_DETALLE = 'CALCULODET_DETALLE';

export const NAVIGATION_TREE = 'NAVIGATION_TREE';
export const NAVIGATION_TREE_PC = 'NAVIGATION_TREE_PC';
export const ID_PC = 'ID_PC';

export const URN_WEB = 'URN_WEB';
export const URN_WEB1 = 'URN_WEB1';

export const PROJECT_LIST_DETAILS = 'PROJECT_LIST_DETAILS';
export const TREE_SELECTEDS = 'TREE_SELECTEDS';

export const AGREGA_REGISTRO = 'AGREGA_REGISTRO';

export const AGREGA_CATEGORIA = 'AGREGA_CATEGORIA';
export const AGREGA_TIPO = 'AGREGA_TIPO';
export const AGREGA_FAMILIA = 'AGREGA_FAMILIA';
export const AGREGA_ELEMENTOS = 'AGREGA_ELEMENTOS';


export const AGREGA_CATEGORIAB = 'AGREGA_CATEGORIAB';
export const AGREGA_TIPOB = 'AGREGA_TIPOB';
export const AGREGA_FAMILIAB = 'AGREGA_FAMILIAB';

export const ADD_CALCULO = 'ADD_CALCULO';
export const UPDATE_CALCULO = 'UPDATE_CALCULO';

export const ADD_ASOCIADO = 'ADD_ASOCIADO';


export const DELETE_ASOCIADO = 'DELETE_ASOCIADO';
export const ASOCIADO_LIMPIAR = 'ASOCIADO_LIMPIAR';

export const ADD_ESTRUCTURA = 'ADD_ESTRUCTURA';
export const DELETE_ESTRUCTURA = 'DELETE_ESTRUCTURA';
export const UPDATE_ESTRUCTURA = 'UPDATE_ESTRUCTURA';

export const AGREGA_GRUPO = 'AGREGA_GRUPO';
export const MODIFICA_GRUPO = 'MODIFICA_GRUPO';
export const ELIMINA_GRUPO = 'ELIMINA_GRUPO';

export const MODIFICA_SUB = 'MODIFICA_SUB';
export const MODIFICA_SUB1 = 'MODIFICA_SUB1';
export const AGREGA_SUB1 = 'AGREGA_SUB1';

export const PONER_PROPS = 'PONER_PROPS';
export const CAMBIAR_FILA_ASOCIADO = 'CAMBIAR_FILA_ASOCIADO';

export const LISTAR_TITULOS = 'LISTAR_TITULOS';
export const LISTAR_PARTIDAS = 'LISTAR_PARTIDAS';

export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
